"""initial schema

Revision ID: 8e6dbdbc8fae
Revises: 
Create Date: 2026-08-22 13:05:55.523647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6dbdbc8fae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_txn_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NETBANKING', 'WALLET', name='payment_method'), nullable=False),
    sa.Column('bank', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_description', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLASSIFIED', 'SCHEDULED', 'RETRYING', 'RECOVERED', 'FAILED_PERMANENTLY', 'NEEDS_USER_ACTION', name='transaction_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_external_txn_id'), 'transactions', ['external_txn_id'], unique=True)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_table('failure_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('INSUFFICIENT_FUNDS', 'BANK_TIMEOUT', 'OTP_MISMATCH', 'CARD_EXPIRED', 'NETWORK_ERROR', 'UNKNOWN', name='failure_category'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.String(length=512), nullable=False),
    sa.Column('classified_by', sa.Enum('RULE_ENGINE', 'LLM', name='classified_by'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_classifications_transaction_id'), 'failure_classifications', ['transaction_id'], unique=False)
    op.create_table('retry_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('RETRY_IMMEDIATE', 'RETRY_SCHEDULED', 'SWITCH_CHANNEL', 'NO_RETRY', name='retry_action'), nullable=False),
    sa.Column('strategy', sa.Enum('SMART', 'NAIVE', name='strategy'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_channel', sa.String(length=32), nullable=True),
    sa.Column('explanation', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_decisions_transaction_id'), 'retry_decisions', ['transaction_id'], unique=False)
    op.create_table('retry_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('channel_used', sa.String(length=32), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.Enum('SUCCESS', 'FAILURE', name='attempt_outcome'), nullable=False),
    sa.Column('resulting_error_code', sa.String(length=64), nullable=True),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['retry_decisions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_attempts_transaction_id'), 'retry_attempts', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retry_attempts_transaction_id'), table_name='retry_attempts')
    op.drop_table('retry_attempts')
    op.drop_index(op.f('ix_retry_decisions_transaction_id'), table_name='retry_decisions')
    op.drop_table('retry_decisions')
    op.drop_index(op.f('ix_failure_classifications_transaction_id'), table_name='failure_classifications')
    op.drop_table('failure_classifications')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_txn_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
